DROP TABLE VENDAS PURGE;

CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');

SELECT ID, produto, categoria, valor, data_venda, vendedor FROM VENDAS;

--////////////////////////\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\//////////////////////////

--EX1. Liste todos os produtos vendidos por “Ana”, ordenados por data.

SELECT id, produto, vendedor
    FROM VENDAS
    WHERE vendedor ='Ana'
    ORDER BY data_venda ASC;


--EX2. Mostre o valor total vendido na categoria “Eletrônicos”.

SELECT SUM(valor) 
    AS total 
    FROM VENDAS 
    WHERE categoria = 'Eletrônicos';


--EX3. Quais produtos custam entre R$200 e R$1000? Mostre nome e valor.

SELECT produto, valor, categoria 
    FROM VENDAS
    WHERE valor >= 200 AND valor <= 1000;


--EX4. Mostre quantas vendas cada vendedor realizou e o valor total vendido por ele, ordenado do maior para o menor faturamento.

SELECT 
    vendedor, 
    COUNT(*) AS total_vendas, 
    SUM(valor) AS valor_total
FROM VENDAS
GROUP BY vendedor
ORDER BY valor_total DESC;